-- Get data from bronze table
SELECT
    *
FROM bronze.USAmericanAirlinesFinancials;

-- Get data from silver table
SELECT
    * INTO silver.Financials_test
FROM bronze.USAmericanAirlinesFinancials;

SELECT
    *
FROM silver.Financials_test;


-- Data quality check and transformation

UPDATE silver.Financials_test
SET 
    Overall_OP_EXPENSES      = COALESCE(TRY_CAST(Overall_OP_EXPENSES AS DECIMAL(18,2)), 0),
    Overall_OP_PROFIT_LOSS   = COALESCE(TRY_CAST(Overall_OP_PROFIT_LOSS AS DECIMAL(18,2)), 0),
    Overall_OP_REVENUES      = COALESCE(TRY_CAST(Overall_OP_REVENUES AS DECIMAL(18,2)), 0),
    Rev_CHARTER_PAX          = COALESCE(TRY_CAST(Rev_CHARTER_PAX AS DECIMAL(18,2)), 0),
    Rev_CHARTER_PROP         = COALESCE(TRY_CAST(Rev_CHARTER_PROP AS DECIMAL(18,2)), 0),
    Rev_MAIL                 = COALESCE(TRY_CAST(Rev_MAIL AS DECIMAL(18,2)), 0),
    Rev_MISC_OP_REV          = COALESCE(TRY_CAST(Rev_MISC_OP_REV AS DECIMAL(18,2)), 0),
    Rev_PROP_BAG             = COALESCE(TRY_CAST(Rev_PROP_BAG AS DECIMAL(18,2)), 0),
    Rev_PROP_FREIGHT         = COALESCE(TRY_CAST(Rev_PROP_FREIGHT AS DECIMAL(18,2)), 0),
    Rev_PUB_SVC_REVENUE      = COALESCE(TRY_CAST(Rev_PUB_SVC_REVENUE AS DECIMAL(18,2)), 0),
    Rev_RES_CANCEL_FEES      = COALESCE(TRY_CAST(Rev_RES_CANCEL_FEES AS DECIMAL(18,2)), 0),
    Rev_TOTAL_CHARTER        = COALESCE(TRY_CAST(Rev_TOTAL_CHARTER AS DECIMAL(18,2)), 0),
    Rev_TOTAL_MISC_REV       = COALESCE(TRY_CAST(Rev_TOTAL_MISC_REV AS DECIMAL(18,2)), 0),
    Rev_TOTAL_PROPERTY       = COALESCE(TRY_CAST(Rev_TOTAL_PROPERTY AS DECIMAL(18,2)), 0),
    Rev_TRANS_REVENUE        = COALESCE(TRY_CAST(Rev_TRANS_REVENUE AS DECIMAL(18,2)), 0),
    Rev_TRANS_REV_PAX        = COALESCE(TRY_CAST(Rev_TRANS_REV_PAX AS DECIMAL(18,2)), 0),
    Exp_AIRCFT_SERVICES      = COALESCE(TRY_CAST(Exp_AIRCFT_SERVICES AS DECIMAL(18,2)), 0),
    Exp_FLYING_OPS           = COALESCE(TRY_CAST(Exp_FLYING_OPS AS DECIMAL(18,2)), 0),
    Exp_GENERAL_ADMIN        = COALESCE(TRY_CAST(Exp_GENERAL_ADMIN AS DECIMAL(18,2)), 0),
    Exp_GENERAL_SERVICES     = COALESCE(TRY_CAST(Exp_GENERAL_SERVICES AS DECIMAL(18,2)), 0),
    Exp_MAINTENANCE          = COALESCE(TRY_CAST(Exp_MAINTENANCE AS DECIMAL(18,2)), 0),
    Exp_PAX_SERVICE          = COALESCE(TRY_CAST(Exp_PAX_SERVICE AS DECIMAL(18,2)), 0),
    Exp_PROMOTION_SALES      = COALESCE(TRY_CAST(Exp_PROMOTION_SALES AS DECIMAL(18,2)), 0),
    Exp_TRANS_EXPENSES       = COALESCE(TRY_CAST(Exp_TRANS_EXPENSES AS DECIMAL(18,2)), 0);


ALTER TABLE silver.Financials_test ALTER COLUMN UNIQUE_CARRIER_NAME NVARCHAR(255);
ALTER TABLE silver.Financials_test ALTER COLUMN YEAR DATETIME2;
ALTER TABLE silver.Financials_test ALTER COLUMN QUARTER INT;
ALTER TABLE silver.Financials_test ALTER COLUMN Overall_OP_EXPENSES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Overall_OP_PROFIT_LOSS DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Overall_OP_REVENUES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_CHARTER_PAX DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_CHARTER_PROP DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_MAIL DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_MISC_OP_REV DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_PROP_BAG DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_PROP_FREIGHT DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_PUB_SVC_REVENUE DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_RES_CANCEL_FEES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_TOTAL_CHARTER DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_TOTAL_MISC_REV DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_TOTAL_PROPERTY DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_TRANS_REVENUE DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Rev_TRANS_REV_PAX DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_AIRCFT_SERVICES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_FLYING_OPS DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_GENERAL_ADMIN DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_GENERAL_SERVICES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_MAINTENANCE DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_PAX_SERVICE DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_PROMOTION_SALES DECIMAL(18,2);
ALTER TABLE silver.Financials_test ALTER COLUMN Exp_TRANS_EXPENSES DECIMAL(18,2);

-- Updating Rev_TOTAL_CHARTER if it's 0
UPDATE silver.Financials_test
SET Rev_TOTAL_CHARTER = Rev_CHARTER_PAX + Rev_CHARTER_PROP
WHERE Rev_TOTAL_CHARTER = 0;

-- Updating Rev_TOTAL_MISC_REV if it's 0
UPDATE silver.Financials_test
SET Rev_TOTAL_MISC_REV = Rev_MISC_OP_REV
WHERE Rev_TOTAL_MISC_REV = 0;

-- Updating Rev_TOTAL_PROPERTY if it's 0
UPDATE silver.Financials_test
SET Rev_TOTAL_PROPERTY = Rev_PROP_BAG + Rev_PROP_FREIGHT
WHERE Rev_TOTAL_PROPERTY = 0;

-- Checking Duplicate Records


SELECT 
    UNIQUE_CARRIER_NAME, 
    YEAR, 
    QUARTER, 
    COUNT(*) AS DuplicateCount
FROM silver.Financials_test
GROUP BY 
    UNIQUE_CARRIER_NAME, 
    YEAR, 
    QUARTER
HAVING COUNT(*) > 1;

-- list the duplicate records 
WITH DuplicatedRecords AS (
    SELECT 
        UNIQUE_CARRIER_NAME, 
        YEAR, 
        QUARTER
    FROM silver.Financials_test
    GROUP BY 
        UNIQUE_CARRIER_NAME, 
        YEAR, 
        QUARTER
    HAVING COUNT(*) > 1
)
SELECT f.UNIQUE_CARRIER_NAME, f.[YEAR], f.[QUARTER], f.Overall_OP_REVENUES
FROM silver.Financials_test f
JOIN DuplicatedRecords d
  ON f.UNIQUE_CARRIER_NAME = d.UNIQUE_CARRIER_NAME
 AND f.YEAR = d.YEAR
 AND f.QUARTER = d.QUARTER
ORDER BY f.UNIQUE_CARRIER_NAME, f.YEAR, f.QUARTER, f.Overall_OP_REVENUES;



